fix

diff --git a/.github/workflows/deploy-aws.yaml b/.github/workflows/deploy-aws.yaml
--- a/.github/workflows/deploy-aws.yaml
+++ b/.github/workflows/deploy-aws.yaml
@@ -1,25 +1,25 @@
-name: Deploy AWS - FastFood App
+name: Deploy AWS Production - FASTFOOD
 
 on:
   push:
     branches:
-      - master
+      - main
 
 env:
   AWS_REGION: us-east-1
-  CLUSTER_NAME: EKS-FIAP-V3
-  ECR_REPO_NAME: fastfood-app
+  CLUSTER_NAME: EKS-FIAP
+  ECR_URI: 039539140324.dkr.ecr.us-east-1.amazonaws.com/fastfood-app
 
 jobs:
-  deploy:
-    name: Deploy App para AWS
+  deploy-production:
+    name: Deploy EKS Production
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout do repositório
+      - name: Checkout Repo
         uses: actions/checkout@v4
 
-      - name: Configurar credenciais da AWS
+      - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -27,42 +27,46 @@ jobs:
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Instalar Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.7
-
-      - name: Criar repositório ECR com Terraform
+      - name: Login ECR
         run: |
-          cd infra
-          terraform init
-          terraform apply -auto-approve
+          aws ecr get-login-password \
+          --region ${{ env.AWS_REGION }} | \
+          docker login --username AWS \
+          --password-stdin \
+          ${{ env.ECR_URI }}
 
-      - name: Obter URL do repositório ECR
-        id: ecr
+      - name: Build and Push Docker Image
         run: |
-          URL=$(aws ecr describe-repositories --repository-names $ECR_REPO_NAME --region $AWS_REGION --query 'repositories[0].repositoryUri' --output text)
-          echo "REPO_URL=$URL" >> $GITHUB_ENV
+          docker build -t fastfood-app .
+          docker tag fastfood-app:latest ${{ env.ECR_URI }}:latest
+          docker push ${{ env.ECR_URI }}:latest
 
-      - name: Login no ECR
+      - name: Update kubeconfig
         run: |
-          aws ecr get-login-password --region $AWS_REGION | \
-          docker login --username AWS --password-stdin $REPO_URL
+          aws eks update-kubeconfig \
+            --region ${{ env.AWS_REGION }} \
+            --name ${{ env.CLUSTER_NAME }}
 
-      - name: Build e Push da imagem Docker
+      - name: Create Secrets in Kubernetes
         run: |
-          docker build -t $ECR_REPO_NAME .
-          docker tag $ECR_REPO_NAME:latest $REPO_URL:latest
-          docker push $REPO_URL:latest
+          kubectl create secret generic fast-food-secrets \
+            --from-literal=DB_USER=${{ secrets.DB_USER }} \
+            --from-literal=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
+            --from-literal=SECRET_KEY=${{ secrets.SECRET_KEY }} \
+            --dry-run=client -o yaml | kubectl apply -f -
 
-      - name: Atualizar kubeconfig
+      - name: Apply Kubernetes Resources
         run: |
-          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
+          kubectl apply -f k8s/configmap.yaml
+          kubectl apply -f k8s/deployment.yaml
+          kubectl apply -f k8s/service.yaml
+          kubectl apply -f k8s/hpa.yaml
+          kubectl apply -f k8s/migrate-job.yaml
 
-      - name: Aplicar configurações no Kubernetes
+      - name: Run Database Migrations Job
         run: |
-          kubectl apply -f https://raw.githubusercontent.com/LuanLiduario/tech-challenge-k8s-terraform/main/k8s/configmap.yaml
-          kubectl apply -f https://raw.githubusercontent.com/LuanLiduario/tech-challenge-k8s-terraform/main/k8s/secrets.yaml
-          kubectl apply -f https://raw.githubusercontent.com/LuanLiduario/tech-challenge-k8s-terraform/main/k8s/deployment.yaml
-          kubectl apply -f https://raw.githubusercontent.com/LuanLiduario/tech-challenge-k8s-terraform/main/k8s/service.yaml
-          kubectl apply -f https://raw.githubusercontent.com/LuanLiduario/tech-challenge-k8s-terraform/main/k8s/hpa.yaml
+          kubectl apply -f k8s/migrate-job.yaml
+          kubectl wait --for=condition=complete --timeout=60s job/fastfood-migrate-job || {
+            echo "Migration job failed or timed out" && kubectl logs job/fastfood-migrate-job && exit 1;
+          }
+          kubectl delete job fastfood-migrate-job || true
